services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-devops
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/home/gokul/.kube:ro
      - ${HOME}/.minikube:/home/gokul/.minikube:ro
    environment:
      HOME: /home/gokul
      MINIKUBE_HOME: /home/gokul/.minikube
      KUBECONFIG: /var/jenkins_home/.kube/config
    networks:
      - default
      - minikube

volumes:
  jenkins_home:

networks:
  minikube:
    external: true
    name: minikube
